# REUSE (https://reuse.software) licensing and copyright fallbacks.
#
# A file's own SPDX header takes priority; these annotations supply the copyright and the licence
# a file does not state for itself. Every file under formatters/ carries an AGPL-3.0-only header
# of its own, so the one annotation here is the MIT default for the rest of the repository.

version = 1
SPDX-PackageName = "ai-tools-assets-tools"
SPDX-PackageDownloadLocation = "https://github.com/dag-node/ai-tools-assets-tools"

[[annotations]]
path = "**"
precedence = "closest"
SPDX-FileCopyrightText = "2026 Ondřej Nedomlel <tools@dagnode.com>"
SPDX-License-Identifier = "MIT"
